### ISSUE TITLE
探测结果对比的疑问?

### ISSUE THREAD

**Issue by Springder** [luy0222/SIRST-5K#1]
你好！ 
我理解咱这个模型是用来生成大量训练数据的，为什么直接跟其他探测算法的结果直接进行对比了？

**Comment by luy0222** [comment]
在结果摆放方式上，我们参照了之前工作的摆放方式。虽然我们生成了大量数据，但是我们没有收集和标注额外的图像。感谢您的意见，我们会考虑和一些DA方法做些进一步的对比和分析。

**Comment by Springder** [comment]
上午拜读了一下你们的文章，我可不可以这样来理解你们的工作。咱的工作其实包括了两部分，一部分是合成数据的生成，给出了一个新的合成方式，另一个工作是在数据生成模型的后面加了一个适配后目标检测的模块。所以即能够生成合成数据，又能够实现目标的检测。最后的实验里面与其他检测方法进行了对比。

**Comment by luy0222** [comment]
非常感谢您对我们工作的关注和理解。您的概括非常准确。我们出了一种新的合成数据生成方法，然后在数据生成模型后加入了一个针对目标检测的适配模块。这样不仅能够生成高质量的合成数据，还能有效地进行目标检测。
