### ISSUE TITLE
训练自己数据集的疑问

### ISSUE THREAD

**Issue by Alan-Rr** [luy0222/SIRST-5K#2]
你好，我尝试用自己的数据集复现您的模型，但是出现了mask读入出错的问题，在train.py中将labels值打印全为0，请问您可以给我一些指导吗？

**Comment by GanGeeee** [comment]
> 你好，我尝试用自己的数据集复现您的模型，但是出现了mask读入出错的问题，在train.py中将labels值打印全为0，请问您可以给我一些指导吗？

他的默认会crop成256*256大小，看这里是不是对应你的mask出错

**Comment by luy0222** [comment]
你好，在小目标检测中，小目标通常只有几个像素点。这里的对labels print输出0代表的是背景，1代表的是目标。为了方便查看和节省空间，默认情况下，输出的tensor会显示部分数据会用省略号代替。即1可能会被省略号替代。所以你print的labels值全为0是正常现象。
如果你想查看目标，具体做法你可以尝试对tensor求和或者print完整tensor来解决。

**Comment by Alan-Rr** [comment]
我是因为训练几个epoch后iou值始终为0，甚至没有波动，才发现读图可能存在问题
